services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - SERVER_HOST=0.0.0.0
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=subscriptions
      - DB_SSLMODE=disable
    depends_on:
      - db
    volumes:
      - ./internal/migration:/app/internal/migration
      - ./config/config.yaml:/app/config/config.yaml
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=subscriptions
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./internal/migration:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  postgres_data: